services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/seerr:/app/config
    restart: unless-stopped
