services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/overseerr:/app/config
    restart: unless-stopped